server:
  port: 8080
spring:
  datasource:
    username: root
    password: asdfghjkl123
    url: jdbc:mysql://localhost:3306/ct?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    host: 162.14.106.166
    port: 6379
    password: asdfghjkl123
    pool:
      max-active: 8
      max-idle: 8
      min-idle: 0
      max-wait: -1

  rabbitmq:
    host: 162.14.106.166
    port: 5672
    virtual-host: ct
    username: myf
    password: 123
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDel
      logic-delete-value: 1
      logic-not-delete-value: 0

oss:
  accessKey: b1KPcG10Ulk_eQK-ymn1ubbnvyERWIaTHtlsh4S7
  secretKey: QuTiyy2xg7WrYwTpByb6g-xmmwBsIDDNsIJNnFhy
  bucket: ct-pro


